---
title: "pacote __Rocc__: gestão e análise de dados de ocorrências de espécies"
author: ""
date: ""
output: pdf_document
---

O pacote __Rocc__(https://liibre.github.io/Rocc/index.html) disponibiliza ferramentas para criar fluxos de trabalho reprodutíveis para tratar dados abertos de ocorrência de espécies. Atualmente existem diversas iniciativas de compilação de bases de dados digitais de biodiversidade, como GBIF no âmbito global e speciesLink no Brasil. Um grande volume de dados está disponível de forma aberta na rede, porém, converter a informação disponível em um dado a ser utilizado em um estudo exige uma combinação de rotinas automatizadas e conhecimento contextual para tomada de decisões. Este pacote se propõe a auxiliar a geração de rotinas automatizadas de obtenção e checagem de dados de biodiversidade usando ferramentas como speciesLink (https://specieslink.net/), Flora do Brasil (http://floradobrasil.jbrj.gov.br/reflora/listaBrasil) e GADM (https://gadm.org/data.html). O objetivo do pacote é automatizar tarefas repetidas e facilitar a tomada de decisão por parte de especialistas e não exclui a necessidade de uma avaliação contextual dos dados. O pacote permite estabelecer um fluxo de trabalho desde a obtenção do dado até a checagem de nomenclatura taxonômica e geográfica e também permite que cada uma das funções seja utilizada de forma independente. 

O pacote __Rocc__ possui três grandes eixos: obtenção de dados de ocorrência, checagem taxonômica e obtenção de dados geográficos. No eixo de obtenção de dados, o pacote possui uma função para fazer download de dados da base do speciesLink, `rspecieslink()`. Essa função se conecta com a API do speciesLink (https://api.splink.org.br/) e permite fazer o download de dados a partir de nomes científicos de espécies ou de municípios brasileiros e na América Latina. Na página do pacote, há um artigo com exemplos de diferentes usos da função _Downloading speciesLink data from R_ (https://liibre.github.io/Rocc/articles/articles/using_rspeciesLink.html). O pacote possui também a função `rgbif2()`, uma função para fazer o download de dados de ocorrência do GBIF (https://www.gbif.org/), que encapsula uma função do pacote rgbif para criar uma saída compatível com o fluxo de trabalho. Uma vez tendo o download de dados das duas fontes, é possível combiná-los usando a função `bind_dwc()`. Isso permite à pessoa usuária obter e combinar dados de diferentes fontes que vêm  de origem seguindo padrões diferentes. Os dados são formatados em uma tabela seguindo os campos do formato DarwinCore, o formato padrão para dados de biodiversidade. 

Além disso, o pacote permite comunicação direta com a base de dados do projeto Flora do Brasil, que é uma iniciativa de catalogação das plantas do Brasil desenvolvida por um comitê de especialistas da área de botânica. __Rocc__ possui uma função para fazer o download da base de dados completa da Flora do Brasil, `update_flora()`. É possível também fazer a busca de listas de espécies seguindo critérios de domínio fitogeográfico onde a espécie ocorre, endemismo, forma de vida ou tipo de vegetação usando a função `search_flora()`. O artigo _Searching for species names in FB2020_ (https://liibre.github.io/Rocc/articles/articles/searching_flora.html) contém exemplos de como usar essas funções.

No eixo de checagem taxonômica __Rocc__ possui três funções. A principal função, `check_string()` permite identificar nomenclatura aberta, categorias infraespecíficas, autoria, espécies indeterminadas, espécies híbridas, caracteres não ascii e dígitos no nome das espécies. Essa função checa um dado nome de espécie e retorna uma sinalização com o status do nome e uma sugestão de correção. Como muitas vezes as bases de dados ou os dados dos próprios pesquisadores vêm de origem com bastante ruído, essa é uma função bastante útil para identificar padrões gerais de inconsistências em dados de espécies. Como a Flora do Brasil é referência para nomes aceitos da flora brasileira, o pacote __Rocc__ permite checagens taxonômicas a partir dela. __Rocc__ possui a função `suggest_flora()` que limpa espaços e corrige erros de digitação de um determinado nome de espécie e `check_flora()` que faz uma requisição direta à API da Flora do Brasil e retorna nomes aceitos e sinônimos para espécies de plantas. No artigo "Building a workflow of taxonomic check" (https://liibre.github.io/Rocc/articles/articles/check_taxa.html) há um exemplo de fluxo de trabalho para uma checagem taxonômica básica. 

Como o dado de biodiversidade corresponde a uma espécie em um dado local, é bastante usual passar os dados por uma checagem geográfica. Como existem diversos pacotes de R desenvolvidos para esse fim, como o coordinateCleaner por exemplo, o pacote __Rocc__ se propõe a efetuar o download de shapefiles e gazetteers que irão auxiliar no processo de checagem geográfica. No eixo de obtenção de dados geográficos o pacote __Rocc__ possui três funções: `getGADM()`, `getGAZ()` e `getWDPA()`. A função `getGADM()` faz o download de shapefiles de unidades administrativas para países do globo a partir de GADM, https://gadm.org/data.html e retorna objetos de classe sf ou sp. A função getGAZ() faz o download do gazetteer do DIVA-GIS (http://www.diva-gis.org/gData). A função `getWDPA()` faz download de shapefiles da base de dados de áreas protegidas da IUCN para cada país (https://www.protectedplanet.net). Diferentemente das funções do pacote que se apoiam em bases como speciesLink e Flora do Brasil, esse eixo do pacote tem escopo global e pode ser aplicado em diferentes contextos. O artigo _Geographic data download with Rocc_ (https://liibre.github.io/Rocc/articles/articles/data_download.html) contém exemplos de uso das funções desse eixo.

A partir dos três eixos do pacote de obtenção de dados de biodiversidade, checagem taxonômica e obtenção de dados geográficos, é possível criar fluxos de trabalho reprodutíveis totalmente baseados em dados abertos para obtenção e limpeza de dados de biodiversidade. Na página do pacote existem artigos para guiar o desenvolvimento de fluxos de trabalho Com isso, espera-se facilitar o acesso a diferentes bases e permitir autononomia às pessoas usuárias de criarem seus próprios fluxos de trabalho adaptados a sua necessidade. O pacote já vem sendo utilizado em projetos acadêmicos e consultorias de listagens de espécies regionais.  Além disso, também tem sido utilizado em aulas de limpeza de dados de biodiversidade. Esperamos com isso, permitir que as pessoas usuárias possam focar seu trabalho mais em seu contexto e no significado biológico e menos em tarefas automatizadas de download e limpeza que já são feitas pelo pacote __Rocc.__ 

__Palavras-chave:__ DIVA-GIS; flora do Brasil; GADM; GBIF; gazetteer; informática da biodiversidade; reprodutibilidade; speciesLink
